### ISSUE TITLE
Add ability to label meal type (e.g. Breakfast, lunch, Dinner, Snack)

### ISSUE THREAD

**Issue by MikeBuran** [vinidy/lemon#43]

**Comment by vinidy** [comment]
I like your other idea about naming a meal but I think this type of tagging (breakfast, lunch, etc) is what will take down companies like myfitnesspal. We are a data-centric company. In 2 years, we should be telling the world when and what people eat based on pure data.

**Comment by MikeBuran** [comment]
Yep, I think that makes good sense.  Let's kill this.
